
server: 
 port: 8080
#9001

# generate the DDL automatically - careful in production
spring:
  jpa:    
    hibernate:
      ddl-auto: none 
  datasource:
    url: jdbc:mysql://localhost:3306/telecom
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver